"""MCP stdio server for the sample_input llm_project_packer bundle.

This file is generated by llm_project_packer's --target cowork export. It is
self-contained: it reads its sibling `index.sqlite` and the parent bundle's
`manifest.json`, `rag_ready/chunks.jsonl`, `assets/`, and `data/` directories.
You can move the whole export folder; the server resolves paths relative to
this script at runtime.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from mcp.server.fastmcp import FastMCP
except ImportError as exc:  # pragma: no cover - import-time guidance only
    raise SystemExit(
        "The 'mcp' package is required to run this server. Install it with:\n"
        "    pip install -r " + str(Path(__file__).resolve().parent / "requirements.txt")
    ) from exc


SERVER_DIR = Path(__file__).resolve().parent
BUNDLE_DIR = SERVER_DIR.parent
INDEX_PATH = SERVER_DIR / "index.sqlite"
MANIFEST_PATH = BUNDLE_DIR / "manifest.json"
CHUNKS_PATH = BUNDLE_DIR / "rag_ready" / "chunks.jsonl"
SOURCE_MAP_PATH = BUNDLE_DIR / "rag_ready" / "source_map.json"
ASSETS_DIR = BUNDLE_DIR / "assets"
DATA_DIR = BUNDLE_DIR / "data"

PROJECT_NAME = 'sample_input'
SERVER_ID = 'fileslicer_sample_input'

mcp = FastMCP(SERVER_ID)


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(str(INDEX_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def _load_manifest() -> List[Dict[str, Any]]:
    if not MANIFEST_PATH.exists():
        return []
    try:
        payload = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    entries = payload.get("entries") if isinstance(payload, dict) else payload
    return list(entries or [])


def _load_source_map() -> Dict[str, Any]:
    if not SOURCE_MAP_PATH.exists():
        return {}
    try:
        return json.loads(SOURCE_MAP_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def _escape_fts_query(query: str) -> str:
    cleaned = query.replace('"', " ").strip()
    if not cleaned:
        return cleaned
    tokens = [token for token in cleaned.split() if token]
    return " ".join(f'"{token}"' for token in tokens)


@mcp.tool()
def list_documents(limit: int = 50, status: Optional[str] = None) -> Dict[str, Any]:
    """List documents recorded in the bundle manifest.

    Args:
        limit: Maximum rows to return (default 50; pass 0 for no cap).
        status: Optional manifest status filter (``ok``, ``skipped``, ``failed``).
    """
    rows = _load_manifest()
    if status:
        rows = [r for r in rows if r.get("status") == status]
    if limit and limit > 0:
        rows = rows[:limit]
    return {"project_name": PROJECT_NAME, "count": len(rows), "documents": rows}


@mcp.tool()
def get_document(doc_id: str) -> Dict[str, Any]:
    """Return the full text of one document by ``DOC_xxxx`` id, reconstructed from its chunks."""
    with _connect() as conn:
        rows = conn.execute(
            "SELECT chunk_id, source_file, source_path, text, token_estimate, ordinal"
            " FROM chunks WHERE doc_id = ? ORDER BY ordinal ASC",
            (doc_id,),
        ).fetchall()
    if not rows:
        return {"doc_id": doc_id, "found": False, "text": ""}
    text = "\n\n".join(r["text"] for r in rows if r["text"])
    return {
        "doc_id": doc_id,
        "found": True,
        "source_file": rows[0]["source_file"],
        "source_path": rows[0]["source_path"],
        "chunk_count": len(rows),
        "token_estimate": sum(int(r["token_estimate"] or 0) for r in rows),
        "text": text,
    }


@mcp.tool()
def search(query: str, limit: int = 10) -> Dict[str, Any]:
    """Run a BM25-ranked SQLite FTS5 keyword search across all chunks.

    Args:
        query: Free-text query. Quoted tokens are matched literally.
        limit: Max hits to return (default 10).
    """
    fts_query = _escape_fts_query(query)
    if not fts_query:
        return {"query": query, "hits": []}
    capped_limit = max(1, min(int(limit or 10), 100))
    with _connect() as conn:
        rows = conn.execute(
            "SELECT chunks_fts.chunk_id AS chunk_id, chunks_fts.doc_id AS doc_id,"
            " chunks_fts.source_file AS source_file,"
            " snippet(chunks_fts, 3, '[[', ']]', '...', 24) AS snippet,"
            " bm25(chunks_fts) AS score"
            " FROM chunks_fts WHERE chunks_fts MATCH ?"
            " ORDER BY score ASC LIMIT ?",
            (fts_query, capped_limit),
        ).fetchall()
    hits = [
        {
            "chunk_id": r["chunk_id"],
            "doc_id": r["doc_id"],
            "source_file": r["source_file"],
            "snippet": r["snippet"],
            "score": float(r["score"]) if r["score"] is not None else None,
        }
        for r in rows
    ]
    return {"query": query, "hit_count": len(hits), "hits": hits}


@mcp.tool()
def get_chunk(chunk_id: str) -> Dict[str, Any]:
    """Return one chunk's text plus the previous/next chunk ids in the same document."""
    with _connect() as conn:
        row = conn.execute(
            "SELECT chunk_id, doc_id, source_file, source_path, text, token_estimate, ordinal"
            " FROM chunks WHERE chunk_id = ?",
            (chunk_id,),
        ).fetchone()
        if row is None:
            return {"chunk_id": chunk_id, "found": False}
        neighbors = conn.execute(
            "SELECT chunk_id, ordinal FROM chunks WHERE doc_id = ? ORDER BY ordinal ASC",
            (row["doc_id"],),
        ).fetchall()
    ordinal = row["ordinal"]
    prev_id = next((n["chunk_id"] for n in neighbors if n["ordinal"] == ordinal - 1), None)
    next_id = next((n["chunk_id"] for n in neighbors if n["ordinal"] == ordinal + 1), None)
    return {
        "chunk_id": row["chunk_id"],
        "doc_id": row["doc_id"],
        "source_file": row["source_file"],
        "source_path": row["source_path"],
        "token_estimate": int(row["token_estimate"] or 0),
        "ordinal": ordinal,
        "previous_chunk_id": prev_id,
        "next_chunk_id": next_id,
        "text": row["text"],
        "found": True,
    }


@mcp.tool()
def get_asset_path(doc_id: str, name: str) -> Dict[str, Any]:
    """Resolve an asset or data file copied for ``doc_id`` to its absolute local path.

    The MCP client (not this server) decides how to use the path. Returns
    ``found=False`` if no matching file exists.
    """
    candidates: List[Path] = []
    asset_root = ASSETS_DIR / doc_id
    if asset_root.exists():
        candidates.append(asset_root / name)
    if DATA_DIR.exists():
        candidates.extend(p for p in DATA_DIR.glob(f"{doc_id}_*") if p.name.endswith(name) or p.name == name)
    for candidate in candidates:
        try:
            resolved = candidate.resolve()
            if resolved.exists() and BUNDLE_DIR in resolved.parents:
                return {
                    "doc_id": doc_id,
                    "name": name,
                    "found": True,
                    "path": str(resolved),
                }
        except OSError:
            continue
    return {"doc_id": doc_id, "name": name, "found": False, "path": None}


if __name__ == "__main__":
    mcp.run()
